
airport_pt_cities = {
    "lisbon",
    "faro",
    "porto"
}

pt_cities = [
  "lisbon",
  "sintra",
  "vila nova de gaia",
  "porto",
  "braga",
  "matosinhos",
  "amadora",
  "almada",
  "oeiras",
  "gondomar",
  "guimarães",
  "odivelas",
  "coimbra",
  "vila franca de xira",
  "maia",
  "setúbal",
  "funchal",
  "viseu",
  "valongo",
  "viana do castelo",
  "paredes",
  "vila do conde",
  "torres vedras",
  "aveiro",
  "queluz",
  "mafra",
  "penafiel",
  "loulé",
  "ponta delgada",
  "moita",
  "faro",
  "póvoa de varzim",
  "palmela",
  "santarém",
  "figueira da foz",
  "felgueiras",
  "paços de ferreira",
  "castelo branco",
  "évora",
  "portimão",
  "pombal",
  "marco de canavezes",
  "vila real",
  "covilhã",
  "caldas da rainha",
  "montijo",
  "rio tinto",
  "fafe",
  "sesimbra",
  "amora",
  "vila verde",
  "lousada",
  "corroios",
  "ourém",
  "olhão",
  "leiria",
  "ponte de lima",
  "santa cruz",
  "guarda",
  "chaves",
  "tomar",
  "ílhavo",
  "trofa",
  "mafamude",
  "ermezinde",
  "silves",
  "torres novas",
  "beja",
  "agualva",
  "câmara de lobos",
  "angra do heroísmo",
  "bragança",
  "esposende",
  "ribeira grande",
  "espinho",
  "lagos",
  "anadia",
  "benavente",
  "massamá",
  "estarreja",
  "lamego",
  "estoril",
  "montemor-o-velho",
  "tavira",
  "odemira",
  "albergaria-a-velha",
  "portalegre",
  "porto de mós",
  "mirandela",
  "vizela",
  "caniço",
  "oliveira do bairro",
  "vale de cambra",
  "arcos de valdevez",
  "póvoa de lanhoso",
  "azambuja",
  "são joão da madeira",
  "cacém",
  "rio maior",
  "praia da vitória",
  "elvas",
  "baião",
  "cinfães",
  "entroncamento",
  "celorico de basto",
  "alfena",
  "soure",
  "monção",
  "vila real de santo antónio",
  "amares",
  "sacavém",
  "lousã",
  "alcochete",
  "montemor-o-novo",
  "peso da régua",
  "condeixa-a-nova",
  "são pedro do sul",
  "ponte de sôr",
  "cabeceiras de basto",
  "quarteira",
  "sertã",
  "macedo de cavaleiros",
  "serpa",
  "castro daire",
  "penacova",
  "moura",
  "nazaré",
  "horta",
  "falagueira",
  "cadaval",
  "estremoz",
  "sines",
  "valença",
  "gouveia",
  "nelas",
  "gafanha da nazaré",
  "arruda dos vinhos",
  "ribeira brava",
  "vila pouca de aguiar",
  "ansião",
  "miranda do corvo",
  "alcácer do sal",
  "vieira do minho",
  "mira",
  "sátão",
  "arcozelo",
  "sever do vouga",
  "tábua",
  "alijó",
  "vendas novas",
  "costa de caparica",
  "óbidos",
  "calheta",
  "resende",
  "vila franca do campo",
  "reguengos de monsaraz",
  "valadares",
  "são brás de alportel",
  "murtosa",
  "moimenta da beira",
  "sobral de monte agraço",
  "trancoso",
  "carregal do sal",
  "idanha-a-nova",
  "pinhel",
  "melgaço",
  "vinhais",
  "almargem",
  "aver-o-mar",
  "ponta do sol",
  "ferreira do zêzere",
  "torre de moncorvo",
  "campo maior",
  "argoncilhe",
  "vila viçosa",
  "proença-a-nova",
  "tarouca",
  "penalva do castelo",
  "são joão da pesqueira",
  "santana",
  "alpiarça",
  "celorico da beira",
  "joane",
  "mondim de basto",
  "miranda do douro",
  "nisa",
  "almodôvar",
  "arraiolos",
  "santa marta de penaguião",
  "vila nova da barquinha",
  "vila nova de foz côa",
  "castelões de cepeda",
  "alvaiázere",
  "poiares",
  "castro verde",
  "mértola",
  "terras de bouro",
  "almeida",
  "redondo",
  "castro marim",
  "ribeira de pena",
  "portel",
  "carrazeda de anciães",
  "sabrosa",
  "tabuaço",
  "povoação",
  "armamar",
  "figueira de castelo rodrigo",
  "são martinho",
  "madalena",
  "monchique",
  "celeiroz",
  "penela",
  "murça",
  "vidigueira",
  "aljezur",
  "alandroal",
  "olival",
  "viana do alentejo",
  "oleiros",
  "penamacor",
  "vila do porto",
  "vila de porto santo",
  "aguiar da beira",
  "golegã",
  "riachos",
  "velas",
  "ourique",
  "vila do bispo",
  "vila nova de paiva",
  "terrujem",
  "alfândega da fé",
  "sousel",
  "fornos de algodres",
  "mora",
  "caranguejeira",
  "nordeste",
  "cuba",
  "real",
  "pampilhosa da serra",
  "lajes",
  "vimioso",
  "avis",
  "mesão frio",
  "valpaços",
  "santa cruz da graciosa",
  "góis",
  "vila nova de milfontes",
  "constância",
  "sardoal",
  "arcozelo",
  "lorvão",
  "pedrógão grande",
  "freixo de espada à cinta",
  "calheta",
  "armação de pêra",
  "vila velha de ródão",
  "marvão",
  "canas de senhorim",
  "tramagal",
  "vila de rei",
  "manteigas",
  "riba de ave",
  "fronteira",
  "castelo de vide",
  "são roque do pico",
  "monforte",
  "valado de frades",
  "fermentelos",
  "castanheira de pêra",
  "arronches",
  "são vicente",
  "trouxemil",
  "ferreiros",
  "trofa",
  "carvoeiro",
  "mourão",
  "alvito",
  "barrancos",
  "caminha",
  "boticas",
  "barcelos",
  "loures",
  "santo tirso",
  "famalicão",
  "cartaxo",
  "fundão",
  "oliveira de azemeis",
  "ovar",
  "lagoa",
  "albufeira",
  "águeda",
  "peniche",
  "borba",
  "marinha grande",
  "salvaterra de magos",
  "barreiro",
  "cascais",
  "ponte da barca",
  "amarante",
  "aljustrel",
  "alcobaça",
  "oliveira do hospital",
  "abrantes",
  "santiago do cacém",
  "cantanhede",
  "grândola",
  "mangualde",
  "arouca",
  "feira",
  "seia",
  "coruche",
  "chamusca",
  "crato",
  "belmonte",
  "vagos",
  "tondela",
  "arganil",
  "gavião",
  "santa comba dão",
  "mogadouro",
  "paredes de coura",
  "seixal",
  "alenquer",
  "mêda",
  "vouzela",
  "mação",
  "trofa",
  "alter do chão",
  "mortágua",
  "bombarral",
  "vila nova de cerveira",
  "sabugal",
  "almeirim",
  "alcanena",
  "mealhada",
  "sernancelhe",
  "batalha",
  "figueiró dos vinhos",
  "vila flor",
  "castelo de paiva",
  "penedono",
  "oliveira de frades",
  "vizela",
  "montalegre",
  "alcoutim",
  "lourinhã",
  "ferreira do alentejo"
]